/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPizzaParty,
  IPizzaPartyInterface,
} from "../../contracts/IPizzaParty";

const _abi = [
  {
    inputs: [],
    name: "getCurrentGameId",
    outputs: [
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
    ],
    name: "getEligibleDailyPlayers",
    outputs: [
      {
        internalType: "address[]",
        name: "eligiblePlayers",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
    ],
    name: "getEligibleWeeklyPlayers",
    outputs: [
      {
        internalType: "address[]",
        name: "eligiblePlayers",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isDailyDrawReady",
    outputs: [
      {
        internalType: "bool",
        name: "ready",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isWeeklyDrawReady",
    outputs: [
      {
        internalType: "bool",
        name: "ready",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "winners",
        type: "address[]",
      },
    ],
    name: "processDailyWinners",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "winners",
        type: "address[]",
      },
    ],
    name: "processWeeklyWinners",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPizzaParty__factory {
  static readonly abi = _abi;
  static createInterface(): IPizzaPartyInterface {
    return new Interface(_abi) as IPizzaPartyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPizzaParty {
    return new Contract(address, _abi, runner) as unknown as IPizzaParty;
  }
}
